FWDUtils.onReady(function(){
	var viewer =  new FWDViewer({
		//----main----//
		divHolderId:"holder360",
		playListAndSkinId:"viewerPlaylistAndSkin",
		displayType:"responsive",
		preloaderText:"Loading 3D object:",
		startDraggingMode:"rotate",
		showLargeImageVersionOnZoom:"yes",
		useEntireScreenFor3dObject:"no",
		stopRotationAtEnds:"no",
		addCorrectionForWebKit:"yes",
		addDragAndSpinSupport:"yes",
		startAtImage:0,
		imageWidth:500,
		imageHeight:500,
		zoomFactor:3,
		dragRotationSpeed:.7,
		dragAndSpinSpeed:.6,
		buttonsRotationSpeed:300,
		slideShowDelay:300,
		backgroundColor:"#FFFFFF",
		preloaderFontColor:"#585858",
		preloaderBackgroundColor:"#FFFFFF",
		//----lightbox-----//
		lightBoxWidth:800,
		lightBoxHeight:550,
		lightBoxBackgroundOpacity:.8,
		lightBoxBackgroundColor:"#000000",
		//----controller----//
		buttons:"rotate, pan, roteteleft, rotateright, scrollbar, play, info, fullscreen",
		buttonsToolTips:"Rotate, Move/Pan, Rotate left, Rotate right, Zoom level: , Play/Pause, Info, Full screen/Normal screen",
		controllerPosition:"bottom",
		inverseNextAndPrevRotation:"yes",
		addKeyboardSupport:"yes",
		slideShowAutoPlay:"no",
		startSpaceBetweenButtons:10,
		spaceBetweenButtons:10,
		startSpaceForScrollBarButtons:20,
		startSpaceForScrollBar:6,
		hideControllerDelay:3,
		controllerMaxWidth:900,
		controllerBackgroundOpacity:1,
		controllerOffsetY:0,
		scrollBarOffsetX:0,
		scrollBarHandlerToolTipOffsetY:4,
		zoomInAndOutToolTipOffsetY:-4,
		buttonsToolTipOffsetY:0,
		link:"http://www.google.com",
		buttonToolTipFontColor:"#585858",
		//----navigator----//
		showNavigator:"yes",
		navigatorPosition:"topleft",
		navigatorOffsetX:6,
		navigatorOffsetY:6,
		navigatorHandlerColor:"#FF0000",
		navigatorBorderColor:"#AAAAAA",
		//----info window----//
		infoWindowBackgroundOpacity:.6,
		infoWindowBackgroundColor:"#FFFFFF",
		infoWindowScrollBarColor:"#585858",
		//----markers-----//
		showMarkersInfo:"no",
		markerToolTipOffsetY:2,
		toolTipWindowMaxWidth:500,
		//----context menu----//
		showScriptDeveloper:"yes",
		contextMenuLabels:"Rotate, Move/Pan, Rotate left, Rotate right, Zoom in/Zoom out, Play/Pause, Info, Full screen/Normal screen",
		contextMenuBackgroundColor:"#d1cfcf",
		contextMenuBorderColor:"#8f8d8d",
		contextMenuSpacerColor:"#acacac",
		contextMenuItemNormalColor:"#585858",
		contextMenuItemSelectedColor:"#FFFFFF",
		contextMenuItemDisabledColor:"#b7b4b4"
	});
});
