<?php
/**
 * The Button for all the share functionality. Buttons are added via css or
 * Javascript via sharethis.
 */
?>
<div class="sharethis-wrapper2">
	<a class='print' href="/print/<?php print $node->nid; ?>" ></a>&nbsp;
	<span class='st_email_large' ></span>&nbsp;
	<!-- <a href="http://www.summitreprints.com" class='reprint' target="_blank"></a> -->
	<span  class='st_sharethis_large'  st_via='automationworld' st_title='<?php echo $title . ' | AW'; ?>'>&nbsp;</span>
</div>
