<?php

/**
 *  Implements hook_ctools_plugin api().
 */
function pmg_youtube_feed_processor_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function pmg_youtube_feed_processor_feeds_plugins() {
  $info = array();
  $path = drupal_get_path('module', 'pmg_youtube_feed_processor') . '/feeds';
  $info['PmgYoutubeFeedProcessor'] = array(
    'name' => 'PMG Youtube Feed Processor',
    'description' => 'Import Youtube Videos into PMG Youtube Feed Video Entity',
    'help' => 'Creates or updates PMG Youtube Feed Videos from feeds.',
    'handler' => array(
      'parent' => 'FeedsProcessor',
      'class' => 'PmgYoutubeFeedProcessor',
      'file' => 'PmgYoutubeFeedProcessor.inc',
      'path' => $path,
    ),
  );

  return $info;
}
