<?php
/**
 * @file
 * pop_up_registration.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function pop_up_registration_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'node-pop_up_registration-body'
  $field_instances['node-pop_up_registration-body'] = array(
    'bundle' => 'pop_up_registration',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
      'teaser' => array(
        'label' => 'hidden',
        'module' => 'text',
        'settings' => array(
          'trim_length' => 600,
        ),
        'type' => 'text_summary_or_trimmed',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'body',
    'label' => 'Body',
    'required' => FALSE,
    'settings' => array(
      'display_summary' => TRUE,
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'module' => 'text',
      'settings' => array(
        'rows' => 20,
        'summary_rows' => 5,
      ),
      'type' => 'text_textarea_with_summary',
      'weight' => 2,
    ),
  );

  // Exported field_instance:
  // 'node-pop_up_registration-field_additional_leadworks_ids'
  $field_instances['node-pop_up_registration-field_additional_leadworks_ids'] = array(
    'bundle' => 'pop_up_registration',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 3,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_additional_leadworks_ids',
    'label' => 'Additional Leadworks IDs',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(),
      'type' => 'number',
      'weight' => 4,
    ),
  );

  // Exported field_instance:
  // 'node-pop_up_registration-field_master_leadworks_id'
  $field_instances['node-pop_up_registration-field_master_leadworks_id'] = array(
    'bundle' => 'pop_up_registration',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 1,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_master_leadworks_id',
    'label' => 'Master Leadworks ID',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(
        'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
      ),
      'type' => 'number',
      'weight' => 3,
    ),
  );

  // Exported field_instance:
  // 'node-pop_up_registration-field_purf_silverpop_event'
  $field_instances['node-pop_up_registration-field_purf_silverpop_event'] = array(
    'bundle' => 'pop_up_registration',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => 'Fire off a Silverpop event for every PURF submission.  This will help with Silverpop drip campaigns.  Simply add the name of the event type in this field.  Write "click" for Silverpop\'s default click event.  <em>Or</em>, if you added a custom event in Silverpop\'s web tracking settings (Settings > Org Admin > Organization Settings in Silverpop), add the name of your custom event here.',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 4,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_purf_silverpop_event',
    'label' => 'Add Silverpop Event',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 6,
    ),
  );

  // Exported field_instance:
  // 'node-pop_up_registration-field_silverpop_program_id'
  $field_instances['node-pop_up_registration-field_silverpop_program_id'] = array(
    'bundle' => 'pop_up_registration',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'number',
        'settings' => array(
          'decimal_separator' => '.',
          'prefix_suffix' => TRUE,
          'scale' => 0,
          'thousand_separator' => ' ',
        ),
        'type' => 'number_integer',
        'weight' => 2,
      ),
      'teaser' => array(
        'label' => 'above',
        'settings' => array(),
        'type' => 'hidden',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'node',
    'field_name' => 'field_silverpop_program_id',
    'label' => 'Silverpop program ID',
    'required' => 0,
    'settings' => array(
      'max' => '',
      'min' => '',
      'prefix' => '',
      'suffix' => '',
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 0,
      'module' => 'number',
      'settings' => array(
        'maxlength_js_label' => 'Content limited to @limit characters, remaining: <strong>@remaining</strong>',
      ),
      'type' => 'number',
      'weight' => 5,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Add Silverpop Event');
  t('Additional Leadworks IDs');
  t('Body');
  t('Fire off a Silverpop event for every PURF submission.  This will help with Silverpop drip campaigns.  Simply add the name of the event type in this field.  Write "click" for Silverpop\'s default click event.  <em>Or</em>, if you added a custom event in Silverpop\'s web tracking settings (Settings > Org Admin > Organization Settings in Silverpop), add the name of your custom event here.');
  t('Master Leadworks ID');
  t('Silverpop program ID');

  return $field_instances;
}
