<?php
/**
 * @author Albert Jankowski <ajankowski@summitmediagroup.com>
 */

/**
 * Implements hook_init()
 */
function kampyle_init() {
  drupal_add_css('http://cf.kampyle.com/k_button.css',array('type' => 'external'));
}

/**
 * Implements hook_page_alter().
 */
function kampyle_page_alter(&$page) {
  //Since Seven is the admin theme don't display it in the admin theme
  if($page['content']['system_main']['#block']->theme != 'seven') {
    $output = <<<EOT

    <!--Start Kampyle Feedback Form Button-->
    <div id="k_close_button" class="k_float kc_bottom kc_right"></div>
    <div>
     <a href="http://www.kampyle.com/"  target="kampyleWindow" id="kampylink" class="k_float k_bottom k_right" onclick="javascript:k_button.open_ff('site_code=8192051&amp;form_id=31618&amp;lang=en');return false;">
       <img src="http://cf.kampyle.com/buttons/en/orange/en-orange-corner-low-right.gif" alt="Feedback Form" border="0"/>
     </a>
    </div>
    <script src="http://cf.kampyle.com/k_button.js" type="text/javascript"></script>
    <!--End Kampyle Feedback Form Button-->
	
EOT;
    $page['page_bottom']['kampyle'] = array('#markup' => $output);
  }
}