<?php
// $Id$
/*
* hook_menu
*/  
function leadwise_menu() {
  $items['admin/config/leadwise'] = array(
    'title' => 'Leadwise Settings',
    'description' => 'leadwise configuration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('leadwise_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['leadwise3rdparty.php'] = array(
    'title' => 'Leadwise',
    'page callback' => 'leadwise_handler',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_init()
 */
function leadwise_init() {
  
  // Excluding cache to a video if it has a leadwise link
  if ($node = menu_get_object('node')) {   
    if(isset($node->field_accela_id['und'][0]['value']) && $node->type == 'video') {
      $GLOBALS['conf']['cache'] = 0;
    }
  }
  
}

/**
 * hook_node_view
 *
 * this will create a render content available in templates, 
 * if this doesnot show up you may print it directly in the node template ex. "print render($content['leadwise'])"
*/
function leadwise_node_view($node, $view_mode) {
  if(!isset($node->field_accela_id[$node->language])) return ;
  
  $redirect_url = $node->field_accela_id[$node->language][0]['value'];
  if (!valid_url($redirect_url)) return ;
  
  switch($node->type.'_'.$view_mode) { 
    case 'webcast_full':
      $node->content['leadwise'] = array(  
        '#markup' => l(t('View Webcast'), $redirect_url, array('attributes' => array('class' => 'blue-button2'))),
        '#weight' =>100,
      );
      break;
    case 'whitepaper_full':
      $node->content['leadwise'] = array(  
        '#markup' => l(t('Download White Paper'), $redirect_url, array('attributes' => array('class' => 'blue-button2'))),
        '#weight' =>100,
      );
      break;
  }
  
}

// applicable to content with viddler only
function leadwise_entity_view_alter(&$build, $type) {
  if ($type == 'node' && $build['#view_mode'] == 'full' 
    && isset($build['field_viddler_id']) && isset($build['field_accela_id'])) {
    if(!isset($_COOKIE["leadwise_referring_url"]) || empty($_COOKIE["leadwise_referring_url"])) {
      
			global $base_root;

			$redirect_url = $build['field_accela_id']['#items'][0]['safe_value'];
      if (!valid_url($redirect_url)) return ;
      
      // cleanup the redirect_url of old contents
      $redirect_url = _leadwise_clean_old_url($redirect_url);
      
      if (isset($_SESSION['leadwise_reader']) && !empty($_SESSION['leadwise_reader'])) {
        $unique_id = $_SESSION['leadwise_reader'];
      }
      else {
        $unique_id = md5(rand());
        $_SESSION['leadwise_reader'] = $unique_id;
      }
      
      // append the unique id
      if (strstr($redirect_url, '?')) {
        $redirect_url .= '&';
      }
      else {
        $redirect_url .= '?';
      }
      
      $redirect_url .= 'id=' . $build['#node']->nid;
       
       //get the video image
      $image_style = 'leadwise';
      $fid = $build['field_viddler_id']['#items'][0]['thumbnail_fid'];
      $file = file_load($fid);
      if(!empty($file)){
        $image = image_style_url($image_style, $file->uri);
        $img = '<img src="'. $image .'">'; 
        $output = l($img, $redirect_url, array('html' => True));
        
        _leadwise_set_cookie('leadwise_enabled', 1);
      } 
      else{
        $output='';
      }
      $build['field_viddler_id'][0]['#markup'] = '' . $output;
      
      
    }
    else {
      $redirect_url = _leadwise_clean_old_url($build['field_accela_id']['#items'][0]['safe_value']);
      if ($redirect_url) {
        if (strstr($redirect_url, '?')) {
          $redirect_url .= '&';
        }
        else {
          $redirect_url .= '?';
        }
        $redirect_url .= 'hidden=true';
				// #1577 - Removing the iframe because it is causing
        // $iframe = '<iframe src="'. $redirect_url . '" height="0px" width="0px" style="visibility:hidden;"></iframe>';
        // $build['field_viddler_id'][0]['#markup'] .= $iframe;

				//Making sure Leadwise redirect cookie is not set
		    if(!isset($_COOKIE["leadwise_redirect"]) || empty($_COOKIE["leadwise_redirect"])) {
				 
				  //To prevent infinite loop create a temporary cookie with an expiration time of 10 seconds
				  _leadwise_set_cookie('leadwise_redirect', 1, 30);
				  //Go to redirect
				  drupal_goto($redirect_url);
				
		    }
				
      }
      
      /*$cookie = @$_COOKIE['leadwise_tracker'];
      _leadwise_set_cookie('leadwise_tracker', $cookie . $build['#node']->nid . ';');
      if ($cookie) {
        $visited_pages = explode(';', $cookie);
        if (!in_array($build['#node']->nid, $visited_pages)) {
          $redirect_url = _leadwise_clean_old_url($build['field_accela_id']['#items'][0]['safe_value']);
          drupal_goto($redirect_url);
        }
      }*/
      
    }
  }
  
}

function _leadwise_clean_old_url($redirect_url) {
  if (!valid_url($redirect_url)) return '';
  
  // cleanup the redirect_url of old contents
  $find = 'http://www.automationworld.com/leadwise3rdparty.php?regurl=';
  if (strstr($redirect_url, $find)) {
    $redirect_url = str_replace($find, '', $redirect_url);
    $redirect_url = urldecode($redirect_url);
  }
  
  return $redirect_url;
}

function leadwise_handler() {
	
  $output='';
  
  //if (isset($_GET["desturl"]) && isset($_GET["id"]) && $_GET["id"] == @$_SESSION['leadwise_reader']) {
  if (isset($_GET["desturl"])) {
		
    $redirect = $_GET['desturl'];
    
    $unique_value = md5(rand()); // just some random character that will not mean anything.
    
    // store the node id
    //$cookie = @$_COOKIE['leadwise_tracker'];
    //_leadwise_set_cookie('leadwise_tracker', $cookie . (int)$_GET['id'] . ';');
    
    _leadwise_set_cookie('leadwise_referring_url', $unique_value);
    drupal_goto($redirect);
  }
  else if (isset($_GET['regurl'])) {
    $redirect_url = $_GET['regurl'];
    // cleanup the redirect_url of old contents
    $find = 'http://www.automationworld.com/leadwise3rdparty.php?regurl=';
    if (strstr($redirect_url, $find)) {
      $redirect_url = str_replace($find, '', $redirect_url);
      $redirect_url = urldecode($redirect_url);
    }
    
    // append the unique id
    if (strstr($redirect_url, '?')) {
      $redirect_url .= '&';
    }
    else {
      $redirect_url .= '?';
    }
    
    $unique_id = md5(rand());
    $redirect_url .= 'id=' . $unique_id;
    _leadwise_set_cookie('leadwise_enabled', 1);
    drupal_goto($redirect_url);
  }

  drupal_goto('<front>');
}

function _leadwise_set_cookie($name, $value, $time = NULL) {
  $expire_time = $expire = variable_get('leadwise_cookie_expire', '0');
  if ($expire) {
    $expire_time = time() + $expire;
  }

	if ($time) {
		$expire_time = time() + $time;
	}
  
  $path = '/';
  setcookie($name, $value, $expire_time);
}

/**
 * admin settings form.
 */
function leadwise_form($form, &$form_state) {
  $form['leadwise_referring_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Leadwise Referring URL'),
    '#description' => t('Where the leadwise production URL is. This allows us to validate the integrity of the redirect.'),
    '#required' => TRUE,
    '#default_value' => variable_get('leadwise_referring_url', ''),
  );
  
  $options = array(
    '0' => 'When browser close',
    '43200' => '12 hours',
    '86400' => '24 hours',
    '604800' => '1 week',
    '2629743' => '1 month',
    '31556926' => '1 year',
    '157784630' => 'Forever',
  );
  
  $form['leadwise_cookie_expire'] = array(
    '#type' => 'select',
    '#title' => t('Cookie Expiration'),
    '#options' => $options,
    '#description' => t('Leadwise referring URL (leadwise.mediadroit.com). Cookie "leadwise_referring_url" is set As long as the refferer URL is coming from this value and the redirect url is valid.'),
    '#required' => TRUE,
    '#default_value' => variable_get('leadwise_cookie_expire', '0'),
  );
  
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save settings'),
  );
  
  return $form;
}

function leadwise_form_submit( $form, &$form_state ) {
  variable_set('leadwise_referring_url', $form_state['values']['leadwise_referring_url']);
  variable_set('leadwise_cookie_expire', $form_state['values']['leadwise_cookie_expire']);
}