<?php
/**
 * @file
 * lia_print_profile.features.field.inc
 */

/**
 * Implementation of hook_field_default_fields().
 */
function lia_print_profile_field_default_fields() {
  $fields = array();

  // Exported field: 'node-leadership_print_profile-body'
  $fields['node-leadership_print_profile-body'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(
        0 => 'node',
      ),
      'field_name' => 'body',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'field_permissions' => array(
          'create' => 'create',
          'edit' => 'edit',
          'edit own' => 'edit own',
          'view' => 'view',
          'view own' => 'view own',
        ),
        'profile2_private' => FALSE,
      ),
      'translatable' => '1',
      'type' => 'text_with_summary',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 0,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'hidden',
          'module' => 'text',
          'settings' => array(
            'trim_length' => 600,
          ),
          'type' => 'text_summary_or_trimmed',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'body',
      'label' => 'Print Copy',
      'required' => 0,
      'settings' => array(
        'display_summary' => 1,
        'text_processing' => '1',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'rows' => '20',
          'summary_rows' => 5,
        ),
        'type' => 'text_textarea_with_summary',
        'weight' => '9',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_address_1'
  $fields['node-leadership_print_profile-field_ld_address_1'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_address_1',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 6,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_address_1',
      'label' => 'Address 1',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '7',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_address_2'
  $fields['node-leadership_print_profile-field_ld_address_2'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_address_2',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 7,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_address_2',
      'label' => 'Address 2',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '9',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_address_city'
  $fields['node-leadership_print_profile-field_ld_address_city'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_address_city',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 8,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_address_city',
      'label' => 'City',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '10',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_categories_technologies'
  $fields['node-leadership_print_profile-field_ld_categories_technologies'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_categories_technologies',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'tid' => array(
          'columns' => array(
            'tid' => 'tid',
          ),
          'table' => 'taxonomy_term_data',
        ),
      ),
      'indexes' => array(
        'tid' => array(
          0 => 'tid',
        ),
      ),
      'module' => 'taxonomy',
      'settings' => array(
        'allowed_values' => array(
          0 => array(
            'parent' => '0',
            'vocabulary' => 'technologies',
          ),
        ),
      ),
      'translatable' => '0',
      'type' => 'taxonomy_term_reference',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'taxonomy',
          'settings' => array(),
          'type' => 'taxonomy_term_reference_link',
          'weight' => 16,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_categories_technologies',
      'label' => 'Technologies',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'term_reference_tree',
        'settings' => array(
          'cascading_selection' => 0,
          'filter_view' => '',
          'leaves_only' => 0,
          'max_depth' => '',
          'parent_term_id' => '',
          'select_parents' => 0,
          'start_minimized' => 0,
          'token_display' => '',
          'track_list' => 0,
        ),
        'type' => 'term_reference_tree',
        'weight' => '3',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_categories_topics'
  $fields['node-leadership_print_profile-field_ld_categories_topics'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '-1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_categories_topics',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'tid' => array(
          'columns' => array(
            'tid' => 'tid',
          ),
          'table' => 'taxonomy_term_data',
        ),
      ),
      'indexes' => array(
        'tid' => array(
          0 => 'tid',
        ),
      ),
      'module' => 'taxonomy',
      'settings' => array(
        'allowed_values' => array(
          0 => array(
            'parent' => '0',
            'vocabulary' => 'topics',
          ),
        ),
      ),
      'translatable' => '0',
      'type' => 'taxonomy_term_reference',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'taxonomy',
          'settings' => array(),
          'type' => 'taxonomy_term_reference_link',
          'weight' => 17,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_categories_topics',
      'label' => 'Topics',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'term_reference_tree',
        'settings' => array(
          'cascading_selection' => 0,
          'filter_view' => '',
          'leaves_only' => 0,
          'max_depth' => '',
          'parent_term_id' => '',
          'select_parents' => 0,
          'start_minimized' => 0,
          'token_display' => '',
          'track_list' => 0,
        ),
        'type' => 'term_reference_tree',
        'weight' => '4',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_company'
  $fields['node-leadership_print_profile-field_ld_company'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_company',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'nid' => array(
          'columns' => array(
            'nid' => 'nid',
          ),
          'table' => 'node',
        ),
      ),
      'indexes' => array(
        'nid' => array(
          0 => 'nid',
        ),
      ),
      'module' => 'node_reference',
      'settings' => array(
        'referenceable_types' => array(
          '360_package_spin_rotate' => 0,
          'article' => 0,
          'blog' => 0,
          'company' => 'company',
          'download' => 0,
          'form_template' => 0,
          'leadership_print_profile' => 0,
          'magazine_covers' => 0,
          'mobile_webform' => 0,
          'page' => 0,
          'playbook' => 0,
          'podcast' => 0,
          'pop_up_registration' => 0,
          'registration_form' => 0,
          'stage_one_form' => 0,
          'video' => 0,
          'webform' => 0,
          'webinar' => 0,
          'webinar_registration' => 0,
          'whitepaper' => 0,
        ),
        'view' => array(
          'args' => array(),
          'display_name' => '',
          'view_name' => '',
        ),
      ),
      'translatable' => '0',
      'type' => 'node_reference',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'node_reference',
          'settings' => array(),
          'type' => 'node_reference_default',
          'weight' => 1,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_company',
      'label' => 'Company',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'node_reference',
        'settings' => array(
          'autocomplete_match' => 'contains',
          'autocomplete_path' => 'node_reference/autocomplete',
          'size' => '60',
        ),
        'type' => 'node_reference_autocomplete',
        'weight' => '1',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_country'
  $fields['node-leadership_print_profile-field_ld_country'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_country',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          'Afghanistan' => 'Afghanistan',
          'Albania' => 'Albania',
          'Algeria' => 'Algeria',
          'Andorra' => 'Andorra',
          'Angola' => 'Angola',
          'Antigua & Deps' => 'Antigua & Deps',
          'Argentina' => 'Argentina',
          'Armenia' => 'Armenia',
          'Australia' => 'Australia',
          'Austria' => 'Austria',
          'Azerbaijan' => 'Azerbaijan',
          'Bahamas' => 'Bahamas',
          'Bahrain' => 'Bahrain',
          'Bangladesh' => 'Bangladesh',
          'Barbados' => 'Barbados',
          'Belarus' => 'Belarus',
          'Belgium' => 'Belgium',
          'Belize' => 'Belize',
          'Benin' => 'Benin',
          'Bhutan' => 'Bhutan',
          'Bolivia' => 'Bolivia',
          'Bosnia Herzegovina' => 'Bosnia Herzegovina',
          'Botswana' => 'Botswana',
          'Brazil' => 'Brazil',
          'Brunei' => 'Brunei',
          'Bulgaria' => 'Bulgaria',
          'Burkina' => 'Burkina',
          'Burundi' => 'Burundi',
          'Cambodia' => 'Cambodia',
          'Cameroon' => 'Cameroon',
          'Canada' => 'Canada',
          'Cape Verde' => 'Cape Verde',
          'Central African Rep' => 'Central African Rep',
          'Chad' => 'Chad',
          'Chile' => 'Chile',
          'China' => 'China',
          'Colombia' => 'Colombia',
          'Comoros' => 'Comoros',
          'Congo' => 'Congo',
          'Congo {Democratic Rep}' => 'Congo {Democratic Rep}',
          'Costa Rica' => 'Costa Rica',
          'Croatia' => 'Croatia',
          'Cuba' => 'Cuba',
          'Cyprus' => 'Cyprus',
          'Czech Republic' => 'Czech Republic',
          'Denmark' => 'Denmark',
          'Djibouti' => 'Djibouti',
          'Dominica' => 'Dominica',
          'Dominican Republic' => 'Dominican Republic',
          'East Timor' => 'East Timor',
          'Ecuador' => 'Ecuador',
          'Egypt' => 'Egypt',
          'El Salvador' => 'El Salvador',
          'Equatorial Guinea' => 'Equatorial Guinea',
          'Eritrea' => 'Eritrea',
          'Estonia' => 'Estonia',
          'Ethiopia' => 'Ethiopia',
          'Fiji' => 'Fiji',
          'Finland' => 'Finland',
          'France' => 'France',
          'Gabon' => 'Gabon',
          'Gambia' => 'Gambia',
          'Georgia' => 'Georgia',
          'Germany' => 'Germany',
          'Ghana' => 'Ghana',
          'Greece' => 'Greece',
          'Grenada' => 'Grenada',
          'Guatemala' => 'Guatemala',
          'Guinea' => 'Guinea',
          'Guinea-Bissau' => 'Guinea-Bissau',
          'Guyana' => 'Guyana',
          'Haiti' => 'Haiti',
          'Honduras' => 'Honduras',
          'Hungary' => 'Hungary',
          'Iceland' => 'Iceland',
          'India' => 'India',
          'Indonesia' => 'Indonesia',
          'Iran' => 'Iran',
          'Iraq' => 'Iraq',
          'Ireland {Republic}' => 'Ireland {Republic}',
          'Israel' => 'Israel',
          'Italy' => 'Italy',
          'Ivory Coast' => 'Ivory Coast',
          'Jamaica' => 'Jamaica',
          'Japan' => 'Japan',
          'Jordan' => 'Jordan',
          'Kazakhstan' => 'Kazakhstan',
          'Kenya' => 'Kenya',
          'Kiribati' => 'Kiribati',
          'Korea North' => 'Korea North',
          'Korea South' => 'Korea South',
          'Kosovo' => 'Kosovo',
          'Kuwait' => 'Kuwait',
          'Kyrgyzstan' => 'Kyrgyzstan',
          'Laos' => 'Laos',
          'Latvia' => 'Latvia',
          'Lebanon' => 'Lebanon',
          'Lesotho' => 'Lesotho',
          'Liberia' => 'Liberia',
          'Libya' => 'Libya',
          'Liechtenstein' => 'Liechtenstein',
          'Lithuania' => 'Lithuania',
          'Luxembourg' => 'Luxembourg',
          'Macedonia' => 'Macedonia',
          'Madagascar' => 'Madagascar',
          'Malawi' => 'Malawi',
          'Malaysia' => 'Malaysia',
          'Maldives' => 'Maldives',
          'Mali' => 'Mali',
          'Malta' => 'Malta',
          'Marshall Islands' => 'Marshall Islands',
          'Mauritania' => 'Mauritania',
          'Mauritius' => 'Mauritius',
          'Mexico' => 'Mexico',
          'Micronesia' => 'Micronesia',
          'Moldova' => 'Moldova',
          'Monaco' => 'Monaco',
          'Mongolia' => 'Mongolia',
          'Montenegro' => 'Montenegro',
          'Morocco' => 'Morocco',
          'Mozambique' => 'Mozambique',
          'Myanmar, {Burma}' => 'Myanmar, {Burma}',
          'Namibia' => 'Namibia',
          'Nauru' => 'Nauru',
          'Nepal' => 'Nepal',
          'Netherlands' => 'Netherlands',
          'New Zealand' => 'New Zealand',
          'Nicaragua' => 'Nicaragua',
          'Niger' => 'Niger',
          'Nigeria' => 'Nigeria',
          'Norway' => 'Norway',
          'Oman' => 'Oman',
          'Pakistan' => 'Pakistan',
          'Palau' => 'Palau',
          'Panama' => 'Panama',
          'Papua New Guinea' => 'Papua New Guinea',
          'Paraguay' => 'Paraguay',
          'Peru' => 'Peru',
          'Philippines' => 'Philippines',
          'Poland' => 'Poland',
          'Portugal' => 'Portugal',
          'Qatar' => 'Qatar',
          'Romania' => 'Romania',
          'Russian Federation' => 'Russian Federation',
          'Rwanda' => 'Rwanda',
          'Saint Vincent & the Grenadines' => 'Saint Vincent & the Grenadines',
          'Samoa' => 'Samoa',
          'San Marino' => 'San Marino',
          'Sao Tome & Principe' => 'Sao Tome & Principe',
          'Saudi Arabia' => 'Saudi Arabia',
          'Senegal' => 'Senegal',
          'Serbia' => 'Serbia',
          'Seychelles' => 'Seychelles',
          'Sierra Leone' => 'Sierra Leone',
          'Singapore' => 'Singapore',
          'Slovakia' => 'Slovakia',
          'Slovenia' => 'Slovenia',
          'Solomon Islands' => 'Solomon Islands',
          'Somalia' => 'Somalia',
          'South Africa' => 'South Africa',
          'Spain' => 'Spain',
          'Sri Lanka' => 'Sri Lanka',
          'St Kitts & Nevis' => 'St Kitts & Nevis',
          'St Lucia' => 'St Lucia',
          'Sudan' => 'Sudan',
          'Suriname' => 'Suriname',
          'Swaziland' => 'Swaziland',
          'Sweden' => 'Sweden',
          'Switzerland' => 'Switzerland',
          'Syria' => 'Syria',
          'Taiwan' => 'Taiwan',
          'Tajikistan' => 'Tajikistan',
          'Tanzania' => 'Tanzania',
          'Thailand' => 'Thailand',
          'Togo' => 'Togo',
          'Tonga' => 'Tonga',
          'Trinidad & Tobago' => 'Trinidad & Tobago',
          'Tunisia' => 'Tunisia',
          'Turkey' => 'Turkey',
          'Turkmenistan' => 'Turkmenistan',
          'Tuvalu' => 'Tuvalu',
          'Uganda' => 'Uganda',
          'Ukraine' => 'Ukraine',
          'United Arab Emirates' => 'United Arab Emirates',
          'United Kingdom' => 'United Kingdom',
          'United States' => 'United States',
          'Uruguay' => 'Uruguay',
          'Uzbekistan' => 'Uzbekistan',
          'Vanuatu' => 'Vanuatu',
          'Vatican City' => 'Vatican City',
          'Venezuela' => 'Venezuela',
          'Vietnam' => 'Vietnam',
          'Yemen' => 'Yemen',
          'Zambia' => 'Zambia',
          'Zimbabwe' => 'Zimbabwe',
        ),
        'allowed_values_function' => '',
      ),
      'translatable' => '0',
      'type' => 'list_text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 10,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_country',
      'label' => 'Country',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '12',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_email'
  $fields['node-leadership_print_profile-field_ld_email'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_email',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 14,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_email',
      'label' => 'Email',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '16',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_fax'
  $fields['node-leadership_print_profile-field_ld_fax'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_fax',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 13,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_fax',
      'label' => 'Fax',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '15',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_phone'
  $fields['node-leadership_print_profile-field_ld_phone'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_phone',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 12,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_phone',
      'label' => 'Phone',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '14',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_print_logo'
  $fields['node-leadership_print_profile-field_ld_print_logo'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_print_logo',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'module' => 'file',
      'settings' => array(
        'display_default' => 0,
        'display_field' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'file',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'file',
          'settings' => array(),
          'type' => 'file_default',
          'weight' => 3,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_print_logo',
      'label' => 'Logo',
      'required' => 0,
      'settings' => array(
        'description_field' => 0,
        'file_directory' => 'ld/print',
        'file_extensions' => 'tif tiff eps jpg jpeg',
        'max_filesize' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'file',
        'settings' => array(
          'progress_indicator' => 'throbber',
        ),
        'type' => 'file_generic',
        'weight' => '5',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_print_photo_1'
  $fields['node-leadership_print_profile-field_ld_print_photo_1'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_print_photo_1',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'module' => 'file',
      'settings' => array(
        'display_default' => 0,
        'display_field' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'file',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'file',
          'settings' => array(),
          'type' => 'file_default',
          'weight' => 4,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_print_photo_1',
      'label' => 'Photo 1',
      'required' => 0,
      'settings' => array(
        'description_field' => 0,
        'file_directory' => 'ld/print',
        'file_extensions' => 'tif tiff eps jpg jpeg',
        'max_filesize' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'file',
        'settings' => array(
          'progress_indicator' => 'throbber',
        ),
        'type' => 'file_generic',
        'weight' => '6',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_print_photo_2'
  $fields['node-leadership_print_profile-field_ld_print_photo_2'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_print_photo_2',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'fid' => array(
          'columns' => array(
            'fid' => 'fid',
          ),
          'table' => 'file_managed',
        ),
      ),
      'indexes' => array(
        'fid' => array(
          0 => 'fid',
        ),
      ),
      'module' => 'file',
      'settings' => array(
        'display_default' => 0,
        'display_field' => 0,
        'uri_scheme' => 'public',
      ),
      'translatable' => '0',
      'type' => 'file',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'file',
          'settings' => array(),
          'type' => 'file_default',
          'weight' => 5,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_print_photo_2',
      'label' => 'Photo 2',
      'required' => 0,
      'settings' => array(
        'description_field' => 0,
        'file_directory' => 'ld/print',
        'file_extensions' => 'tif tiff eps jpg jpeg',
        'max_filesize' => '',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'file',
        'settings' => array(
          'progress_indicator' => 'throbber',
        ),
        'type' => 'file_generic',
        'weight' => '7',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_state'
  $fields['node-leadership_print_profile-field_ld_state'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_state',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(),
      'indexes' => array(
        'value' => array(
          0 => 'value',
        ),
      ),
      'module' => 'list',
      'settings' => array(
        'allowed_values' => array(
          'AB' => 'Alberta',
          'AK' => 'Alaska',
          'AR' => 'Arkansas',
          'AS' => 'American Samoa',
          'AZ' => 'Arizona',
          'BC' => 'British Columbia',
          'CA' => 'California',
          'CO' => 'Colorado',
          'CT' => 'Connecticut',
          'DC' => 'District of Columbia',
          'DE' => 'Delaware',
          'FL' => 'Florida',
          'FM' => 'Fed. States of Micronesia',
          'GA' => 'Georgia',
          'GU' => 'Guam',
          'HI' => 'Hawaii',
          'IA' => 'Iowa',
          'ID' => 'Idaho',
          'IL' => 'Illinois',
          'IN' => 'Indiana',
          'KS' => 'Kansas',
          'KY' => 'Kentucky',
          'LA' => 'Louisiana',
          'MA' => 'Massachusetts',
          'MB' => 'Manitoba',
          'MD' => 'Maryland',
          'ME' => 'Maine',
          'MH' => 'Marshall Islands',
          'MI' => 'Michigan',
          'MN' => 'Minnesota',
          'MO' => 'Missouri',
          'MP' => 'Northern Mariana Is.',
          'MS' => 'Mississippi',
          'MT' => 'Montana',
          'NB' => 'New Brunswick',
          'NC' => 'North Carolina',
          'ND' => 'North Dakota',
          'NE' => 'Nebraska',
          'NF' => 'Newfoundland',
          'NH' => 'New Hampshire',
          'NJ' => 'New Jersey',
          'NM' => 'New Mexico',
          'NS' => 'Nova Scotia',
          'NT' => 'Northwest Territories',
          'NV' => 'Nevada',
          'NY' => 'New York',
          'OH' => 'Ohio',
          'OK' => 'Oklahoma',
          'ON' => 'Ontario',
          'OR' => 'Oregon',
          'PA' => 'Pennsylvania',
          'PE' => 'Prince Edward Island',
          'PR' => 'Puerto Rico',
          'PW' => 'Palau',
          'QC' => 'Quebec',
          'RI' => 'Rhode Island',
          'SC' => 'South Carolina',
          'SD' => 'South Dakota',
          'SK' => 'Saskatchewan',
          'TN' => 'Tennessee',
          'TX' => 'Texas',
          'UT' => 'Utah',
          'VA' => 'Virginia',
          'VI' => 'Virgin Islands',
          'VT' => 'Vermont',
          'WA' => 'Washington',
          'WI' => 'Wisconsin',
          'WV' => 'West Virginia',
          'WY' => 'Wyoming',
          'YT' => 'Yukon',
          '\\AL' => 'Alabama',
        ),
        'allowed_values_function' => '',
      ),
      'translatable' => '0',
      'type' => 'list_text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 9,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_state',
      'label' => 'State',
      'required' => 0,
      'settings' => array(
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(),
        'type' => 'options_select',
        'weight' => '11',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_website'
  $fields['node-leadership_print_profile-field_ld_website'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_website',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 15,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_website',
      'label' => 'Website',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '17',
      ),
    ),
  );

  // Exported field: 'node-leadership_print_profile-field_ld_zip_postal_code'
  $fields['node-leadership_print_profile-field_ld_zip_postal_code'] = array(
    'field_config' => array(
      'active' => '1',
      'cardinality' => '1',
      'deleted' => '0',
      'entity_types' => array(),
      'field_name' => 'field_ld_zip_postal_code',
      'field_permissions' => array(
        'type' => '0',
      ),
      'foreign keys' => array(
        'format' => array(
          'columns' => array(
            'format' => 'format',
          ),
          'table' => 'filter_format',
        ),
      ),
      'indexes' => array(
        'format' => array(
          0 => 'format',
        ),
      ),
      'module' => 'text',
      'settings' => array(
        'max_length' => '255',
      ),
      'translatable' => '0',
      'type' => 'text',
    ),
    'field_instance' => array(
      'bundle' => 'leadership_print_profile',
      'default_value' => NULL,
      'deleted' => '0',
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'text',
          'settings' => array(),
          'type' => 'text_default',
          'weight' => 11,
        ),
        'jquerymobile_teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => 'node',
      'field_name' => 'field_ld_zip_postal_code',
      'label' => 'Zip/Postal Code',
      'required' => 0,
      'settings' => array(
        'text_processing' => '0',
        'user_register_form' => FALSE,
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'text',
        'settings' => array(
          'size' => '60',
        ),
        'type' => 'text_textfield',
        'weight' => '13',
      ),
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Address 1');
  t('Address 2');
  t('City');
  t('Company');
  t('Country');
  t('Email');
  t('Fax');
  t('Logo');
  t('Phone');
  t('Photo 1');
  t('Photo 2');
  t('Print Copy');
  t('State');
  t('Technologies');
  t('Topics');
  t('Website');
  t('Zip/Postal Code');

  return $fields;
}
