<?php

/**
 * Implementation of hook_menu().
 */
function imcemup_menu() {
  $items = array();
  $items['imcemup'] = array(
    'title' => 'File browser',
    'page callback' => 'imcemup_imce',
    'access callback' => 'imcemup_access',
    'type' => MENU_CALLBACK,
    'file' => 'imcemup.inc'
  );
  return $items;
}

/**
 * Implementation of hook_init().
 */
function imcemup_init() {
  // Allow flash uploader to access to imcemup path in maintenance mode.
  if (variable_get('maintenance_mode', 0) && $_GET['q'] === 'imcemup') {
    $GLOBALS['conf']['maintenance_mode'] = 0;
  }
}

/**
 * Implementation of hook_form_formID_alter().
 */
function imcemup_form_imce_profile_form_alter(&$form, &$form_state) {
  $form['profile']['mupnum'] = array(
    '#type' => 'textfield',
    '#title' => t('Miltiple upload limit'),
    '#default_value' => $form_state['profile']['mupnum'],
    '#description' => t('Set the maximum number of simultaneous uploads. If this is smaller than 2, the regular upload form will be used instead of the Flash uploader that enables selecting and uploading multiple files.'),
  );
}

/**
 * Custom profile process.
 */
function imcemup_process_profile(&$imce) {
  $imce['mupnum'] = (int) $imce['mupnum'];
}

/**
 * Custom content.
 */
function imcemup_imce_content(&$imce) {
  if (!$imce['error'] && imce_perm_exists($imce, 'upload') && $imce['mupnum'] > 1) {
    include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'imcemup') . '/imcemup.inc';
    return _imcemup_imce_content($imce);
  }
}

/**
 * Upload path access check
 */
function imcemup_access() {
  if (!isset($_POST['_uid']) || !isset($_POST['_token']) || !isset($_POST['_dir'])) {
    return FALSE;
  }
  include_once DRUPAL_ROOT . '/' . drupal_get_path('module', 'imcemup') . '/imcemup.inc';
  return _imcemup_access();
}